# azure-pipelines-trigger.yml
name: SecondPipeline 

trigger: none

# this pipeline will be triggered by another pipeline
resources:
  pipelines:
  - pipeline: azure-pipelines-1.yml   # Name of the pipeline resource
    source: azure-pipelines-1.yml # Name of the pipeline referenced by the pipeline resource
    project: Trigger-Pipeline-From-Another-Pipeline # Required only if the source pipeline is in another project
    trigger: true # enable the trigger

pool:
   name: Ubuntu-maven

steps:
  - script: echo This pipeline was set to be triggered after first pipeline completes.