name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: [self-hosted, Linux]
    steps:
      - uses: actions/checkout@v4
